/**
 * Source of the dev-only SSR bootstrap injected into the `ng serve` server
 * bundle (see `plugin/dev-host-instances-plugin.ts`).
 *
 * Under `ng serve` the host loads via Vite's SSR runner while a remote loads via
 * the orchestrator's Node loader — two `@angular/core` instances → NG0203. The
 * fix shares the instance: `hostInstances` has the orchestrator publish the
 * host's singletons and re-export them to remotes. We pass our own `load` so
 * instances are captured in *this* (the host's) realm, not the orchestrator's,
 * which under Vite SSR differs. (Production dedupes via the import map instead.)
 */
export interface DevHostInstancesOptions {
  /** Browser output dir relative to the workspace root, e.g. `dist/host/browser`. */
  relBrowserPath: string;
  /**
   * Origin of the running dev server, e.g. `http://localhost:4200`. Under
   * `ng serve` the federation manifest lives only in Vite's memory (never on
   * disk), so it has to be fetched over HTTP from this origin. Omit for
   * non-serve builds, where the manifest is read from `relBrowserPath` on disk.
   */
  devServerOrigin?: string;
}

export function generateDevHostInstancesEntry({
  relBrowserPath,
  devServerOrigin,
}: DevHostInstancesOptions): string {
  // relBrowserPath is resolved against process.cwd() (the workspace root under
  // `ng serve`), where the federation build writes its artifacts.
  return `// Generated by @angular-architects/native-federation-v4 (dev SSR) — do not edit.
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const browserDir = join(process.cwd(), ${JSON.stringify(relBrowserPath)});
const manifestPath = join(browserDir, 'federation.manifest.json');
const devServerOrigin = ${JSON.stringify(devServerOrigin ?? null)};

// Under \`ng serve\` Vite serves the federation manifest (and remote entries)
// from memory and never writes them to disk, so prefer the dev server's own
// origin over the never-present on-disk path.
const hostRemoteEntry = devServerOrigin
  ? devServerOrigin + '/remoteEntry.json'
  : join(browserDir, 'remoteEntry.json');

// The orchestrator's readSourceBytes resolves http(s):// manifests and remote
// entries, but a static host returns 404 for the manifest — fetch it here so
// that 404 degrades to an empty manifest (which still bridges host singletons)
// instead of failing init. With no known origin, fall back to the on-disk path.
async function resolveManifest() {
  if (devServerOrigin) {
    try {
      const res = await fetch(devServerOrigin + '/federation.manifest.json');
      if (res.ok) return await res.json();
      return {};
    } catch {
      // Origin unreachable — fall through to the on-disk path.
    }
  }
  return existsSync(manifestPath) ? manifestPath : {};
}

const g = globalThis;

if (!g['__NF_HOST_SERVER_LOADER__']) {
  const { initNodeFederation } = await import('@softarc/native-federation-orchestrator/node');

  let loadRemoteModule;
  let initError;
  try {
    ({ loadRemoteModule } = await initNodeFederation(
      await resolveManifest(),
      {
        hostRemoteEntry,
        // load through THIS module's graph so we capture the host's instances,
        // not the orchestrator realm's (which differs under Vite SSR).
        hostInstances: { load: (s) => import(/* @vite-ignore */ s) },
      },
    ));
  } catch (err) {
    initError = err;
  }

  // Published iff the bridge actually ran. If not, fail fast — a missing bridge
  // surfaces as an intermittent, hard-to-trace NG0203 instead.
  const published = g['__NF_HOST_INSTANCES__'];
  const bridged = published && Object.keys(published).length > 0;
  if (!bridged) {
    throw new Error(
      '[native-federation] dev SSR host-instance bridge did not engage — ' +
      'globalThis.__NF_HOST_INSTANCES__ was not published. Usually ' +
      "'@softarc/native-federation-orchestrator/node' was bundled by Vite " +
      'instead of externalized (so its module.register() loader never ran), ' +
      'or the installed orchestrator predates the hostInstances bridge.' +
      (initError ? ' Cause: ' + (initError && initError.message || initError) : ''),
    );
  }

  // Bridge ran but init failed (e.g. a remote is down): render without remotes.
  if (initError) {
    console.warn(
      '[native-federation] dev SSR: federation init failed; rendering host without remotes:',
      initError && initError.message || initError,
    );
  } else {
    g['__NF_HOST_SERVER_LOADER__'] = loadRemoteModule;
  }
}
`;
}
