/**
 * Source of the dev-only SSR bootstrap injected into the `ng serve` server
 * bundle (see `plugin/dev-host-instances-plugin.ts`).
 *
 * Under `ng serve` the host loads via Vite's SSR runner while a remote loads via
 * the orchestrator's Node loader — two `@angular/core` instances → NG0203. The
 * fix shares the instance: `hostInstances` has the orchestrator publish the
 * host's singletons and re-export them to remotes. We pass our own `load` so
 * instances are captured in *this* (the host's) realm, not the orchestrator's,
 * which under Vite SSR differs. (Production dedupes via the import map instead.)
 */
export interface DevHostInstancesOptions {
  /** Browser output dir relative to the workspace root, e.g. `dist/host/browser`. */
  relBrowserPath: string;
}

export function generateDevHostInstancesEntry({ relBrowserPath }: DevHostInstancesOptions): string {
  // relBrowserPath is resolved against process.cwd() (the workspace root under
  // `ng serve`), where the federation build writes its artifacts.
  return `// Generated by @angular-architects/native-federation-v4 (dev SSR) — do not edit.
import { existsSync } from 'node:fs';
import { join } from 'node:path';

const browserDir = join(process.cwd(), ${JSON.stringify(relBrowserPath)});
const manifestPath = join(browserDir, 'federation.manifest.json');
const hostRemoteEntry = join(browserDir, 'remoteEntry.json');

const g = globalThis;

if (!g['__NF_HOST_SERVER_LOADER__']) {
  const { initNodeFederation } = await import('@softarc/native-federation-orchestrator/node');

  let loadRemoteModule;
  let initError;
  try {
    ({ loadRemoteModule } = await initNodeFederation(
      // Static host has no manifest; an empty one still bridges host singletons.
      existsSync(manifestPath) ? manifestPath : {},
      {
        hostRemoteEntry,
        // load through THIS module's graph so we capture the host's instances,
        // not the orchestrator realm's (which differs under Vite SSR).
        hostInstances: { load: (s) => import(/* @vite-ignore */ s) },
      },
    ));
  } catch (err) {
    initError = err;
  }

  // Published iff the bridge actually ran. If not, fail fast — a missing bridge
  // surfaces as an intermittent, hard-to-trace NG0203 instead.
  const published = g['__NF_HOST_INSTANCES__'];
  const bridged = published && Object.keys(published).length > 0;
  if (!bridged) {
    throw new Error(
      '[native-federation] dev SSR host-instance bridge did not engage — ' +
      'globalThis.__NF_HOST_INSTANCES__ was not published. Usually ' +
      "'@softarc/native-federation-orchestrator/node' was bundled by Vite " +
      'instead of externalized (so its module.register() loader never ran), ' +
      'or the installed orchestrator predates the hostInstances bridge.' +
      (initError ? ' Cause: ' + (initError && initError.message || initError) : ''),
    );
  }

  // Bridge ran but init failed (e.g. a remote is down): render without remotes.
  if (initError) {
    console.warn(
      '[native-federation] dev SSR: federation init failed; rendering host without remotes:',
      initError && initError.message || initError,
    );
  } else {
    g['__NF_HOST_SERVER_LOADER__'] = loadRemoteModule;
  }
}
`;
}
