/**
 * Source of the Angular-free SSR entry that the build emits as
 * `dist/<app>/server/server.mjs`.
 *
 * Why this exists: the Angular CLI prepends the `@angular/ssr` app-engine
 * manifest registration to the emitted server entry, so the entry's *static*
 * import graph pulls in `@angular/*`. ESM evaluates a module's entire static
 * graph before its body runs, so Angular would load from `node_modules`
 * (unmapped, partially compiled) before any `initNodeFederation()` could
 * register the node loader — yielding two `@angular/core` instances (NG0203)
 * or `JIT compilation failed`.
 *
 * The fix: the build renames Angular's emitted `server.mjs` (which carries the
 * injected app-engine registration and the whole Angular graph) to
 * `bootstrap-server.mjs`, and writes this file as the new `server.mjs`. Its
 * static graph is Angular-free (orchestrator `/node` + Node builtins only), so
 * `initNodeFederation()` runs and registers the loader *before* the
 * `bootstrap-server.mjs` graph — including the injected `@angular` — is
 * dynamically imported and evaluated. From that point every `@angular/*`
 * resolves to the single shared federated chunk.
 */
export const federationServerEntry = `// Generated by @angular-architects/native-federation-v4 — do not edit.
// Angular-free entry: registers the federation node loader BEFORE any
// '@angular/*' module is evaluated, then hands off to the real server bundle.
import { initNodeFederation } from '@softarc/native-federation-orchestrator/node';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const serverDir = dirname(fileURLToPath(import.meta.url));
const browserDir = join(serverDir, '../browser');

// 'federation.manifest.json' lists the remotes for a (dynamic) host. Static
// hosts have no manifest file; an empty manifest still lets the orchestrator
// register the host's own shared externals via 'hostRemoteEntry', which is what
// dedupes '@angular/*'.
const manifestPath = join(browserDir, 'federation.manifest.json');
const hostRemoteEntry = pathToFileURL(join(browserDir, 'remoteEntry.json')).href;

try {
  const { loadRemoteModule } = await initNodeFederation(
    existsSync(manifestPath) ? manifestPath : {},
    { hostRemoteEntry },
  );
  // Bridge the server-side loader to the application (read by the host's SSR
  // render code, e.g. an injected LOAD_REMOTE_MODULE token).
  globalThis['__NF_HOST_SERVER_LOADER__'] = loadRemoteModule;
} catch (err) {
  console.warn(
    '[native-federation] initNodeFederation failed; SSR will render without federated remotes:',
    (err && err.message) || err,
  );
}

// The imported server bundle only calls app.listen() when it is the main module
// or when pm_id is set; it is now imported (not main), so opt it into listening.
process.env['pm_id'] ??= '1';

await import('./bootstrap-server.mjs');
`;
